# Generated by Django 5.2.7 on 2025-12-28 19:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destinatario', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
